const detect = require ('./index');

const detectAndLog = e =>
  detect (e).then (res =>
    console.log (e.substring (0, 25) + `... Language: ${res.match_language}`)
  );

[
  `Rikssvenska, eller standardsvenska, är det standardspråk som i Sverige sedan 1800-talet utvecklats ur mellansvenska dialekter och var väletablerad vid början av 1900-talet. Det finlandssvenska standardspråket, högsvenskan, har ett eget språkvårdsorgan, som dock strävar efter att hålla skillnaden till rikssvenskan liten. Regionala varianter med rötter i äldre lokala dialekter talas fortfarande, men både talspråk och särskilt skriftspråk är i hög grad standardiserade i fråga om grammatik och ordförråd. Även mer särpräglade dialekter talas i mindre utsträckning. De är inte direkt hotade av språkdöd, men har varit på tillbakagång sedan början av 1900-talet, trots att många är välutforskade och att användningen idag inte längre motarbetas.`,
  `В России проживает более 190 народов, которые пишут и читают на 60 литературных языках. Но что мы знаем об этих литературах, помимо русской? Между тем, творчество современных авторов, представляющих различные народы России, охватывает широкий спектр стилей и жанров – это и поэзия, и проза, фольклор, и детская литература, реализм, постмодернизм и даже рэп-п`,
  `Fonetiškai ir morfologiškai konservatyvi lietuvių kalba žymiai artimesnė baltų prokalbei negu naujoviškesnė latvių kalba. Lietuvių kalba – archajiškiausia iš gyvųjų indoeuropiečių kalbų, išsaugojusi daugybę indoeuropiečių prokalbės ypatybių. Lietuvių kalba skirstoma į dvi pagrindines tarmes: aukštaičių ir žemaičių. Dabartinė bendrinė lietuvių kalba grindžiama vakarų aukštaičių kauniškių patarme.Lietuvių kalboje yra 45 priebalsinės ir 13 balsinių fonemų`,
  `Genealogisen eli kielen alkuperään perustuvan luokittelun mukaan suomen kieli kuuluu uralilaisen kielikuntaan. Uralilaisia kieliä on parisenkymmentä, ja niitä puhutaan Euroopan pohjois- ja itäosissa, Unkarissa ja sen lähialueilla sekä Siperiassa. Ne voidaan jakaa kahteen pääryhmään, suomalais-ugrilaisiin kieliin ja samojedikieliin. Suomen lähimpiä sukukieliä ovat itämerensuomalaiset kielet, kuten viro ja karjala. Kaukaisempaa sukua ovat esimerkiksi saamelaiskielet ja unkari. Uralilaiset kielet ovat kehittyneet uralilaisesta kantakielestä.`,
  `English is a West Germanic language that was first spoken in early medieval England and eventually became a global lingua franca.[4][5] It is named after the Angles, one of the Germanic tribes that migrated to the area of Great Britain that later took their name, as England. Both names derive from Anglia, a peninsula in the Baltic Sea. The language is closely related to Frisian and Low Saxon, and its vocabulary has been significantly influenced by other Germanic languages, particularly Norse (a North Germanic language), and to a greater extent by Latin and French.`,
  `Elkeen het die reg tot opvoeding. Opvoeding sal gratis wees, ten minste in die elementêre en fundamentele stadiums. Elementêre opvoeding sal verpligtend wees. Tegniese en professionele opvoeding sal geredelik beskikbaar wees en ho‘r opvoeding sal net so geredelik op meriete beskikbaar wees.`,
].map (detectAndLog);
